FROM durst/csgo-no-update-base:0.1
USER root
# DONT INSTALL c++, g++ works but c++ crashes for some reason
RUN apt-get -y update && \
    apt-get -y install less procps unzip zip python3 jq libgomp1 make gcc g++ git libssl-dev gdb libopencv-dev python3-opencv cmake libhdf5-dev neovim
RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.sh && \
    chmod a+x cmake-3.22.2-linux-x86_64.sh && \
    mkdir cmake && \
    ./cmake-3.22.2-linux-x86_64.sh --skip-license --prefix=cmake && \
    update-alternatives --install /usr/bin/cmake cmake ${HOMEDIR}/cmake/bin/cmake 60
USER $USER
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip
USER root
RUN ./aws/install
USER $USER
ADD ./install_sourcemod.sh ${HOMEDIR}/install_sourcemod.sh
RUN ${HOMEDIR}/install_sourcemod.sh ${NONVOLUMESTEAMAPPDIR}/csgo
ADD ./install_link.sh ${HOMEDIR}/install_link.sh
RUN ${HOMEDIR}/install_link.sh 
RUN git clone https://github.com/David-Durst/csknow.git 
ADD ./internal_scripts/server.cfg ${NONVOLUMESTEAMAPPDIR}/csgo/cfg/server.cfg
ADD ./internal_scripts/gamemode_competitive.cfg ${NONVOLUMESTEAMAPPDIR}/csgo/cfg/gamemode_competitive.cfg
ADD ./internal_scripts/gamemode_competitive_server.cfg ${NONVOLUMESTEAMAPPDIR}/csgo/cfg/gamemode_competitive_server.cfg
ADD ./internal_scripts/gamemode_casual_server.cfg ${NONVOLUMESTEAMAPPDIR}/csgo/cfg/gamemode_casual_server.cfg
ADD ./internal_scripts/docker_run_csgo_bots.sh ${NONVOLUMESTEAMAPPDIR}/docker_run_csgo_bots.sh
ADD ./maps/bot_playground.bsp ./maps/bot_playground.nav \
    ./maps/bot_playground_2v1.bsp ./maps/bot_playground_2v1.nav ${NONVOLUMESTEAMAPPDIR}/csgo/maps/
ADD ./entry.sh ${HOMEDIR}/entry.sh
ADD ./upload_logs.py ${HOMEDIR}/upload_logs.py
RUN { \
        echo '@ShutdownOnFailedCommand 1'; \
        echo '@NoPromptForPassword 1'; \
        echo 'force_install_dir '"${NONVOLUMESTEAMAPPDIR}"''; \
        echo 'login anonymous'; \
        echo 'app_update '"${STEAMAPPID}"''; \
        echo 'quit'; \
    } > "${HOMEDIR}/${STEAMAPP}_update.txt"
CMD ["bash", "entry.sh"]
