
#319_titan-epsilon_de_dust2
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_EPSILONMAJ3R_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON MAJ3R" "apEX[D],,Ex6TenZ,kennyS,Maniac,KQLY" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_apEXD_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "apEX[D]" "EPSILON MAJ3R,,EPSILON • SIXER/j/,EPSILON • ScreaM -R-,EPSILON • Uzzziii * ViewSonic,EPSILON G[M]X * Nike" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_EPSILONSIXERj_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON • SIXER/j/" "apEX[D],,Ex6TenZ,kennyS,Maniac,KQLY" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_EPSILONUzzziiiViewSonic_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON • Uzzziii * ViewSonic" "apEX[D],,Ex6TenZ,kennyS,Maniac,KQLY" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_Ex6TenZ_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Ex6TenZ" "EPSILON MAJ3R,,EPSILON • SIXER/j/,EPSILON • ScreaM -R-,EPSILON • Uzzziii * ViewSonic,EPSILON G[M]X * Nike" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_EPSILONGMXNike_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON G[M]X * Nike" "apEX[D],,Ex6TenZ,kennyS,Maniac,KQLY" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_EPSILONScreaMR_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON • ScreaM -R-" "apEX[D],,Ex6TenZ,kennyS,Maniac,KQLY" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_Maniac_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Maniac" "EPSILON MAJ3R,,EPSILON • SIXER/j/,EPSILON • ScreaM -R-,EPSILON • Uzzziii * ViewSonic,EPSILON G[M]X * Nike" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_KQLY_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "KQLY" "EPSILON MAJ3R,,EPSILON • SIXER/j/,EPSILON • ScreaM -R-,EPSILON • Uzzziii * ViewSonic,EPSILON G[M]X * Nike" 2 319_titan-epsilon_de_dust2.dem ${pass}
python computeVisibility.py ${script_dir}/videos/319_titan-epsilon_de_dust2/319_titan-epsilon_de_dust2_kennyS_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "kennyS" "EPSILON MAJ3R,,EPSILON • SIXER/j/,EPSILON • ScreaM -R-,EPSILON • Uzzziii * ViewSonic,EPSILON G[M]X * Nike" 2 319_titan-epsilon_de_dust2.dem ${pass}



#334_natus-vincere-team-ldlc_de_inferno
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_seized_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "seized" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC SMITHZZ * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC Happy * CMSTORM" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_LDLCNBeardKCMSTORM_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC NBeardK- * CMSTORM" "seized,,Zeu$,Edward,starix,GuardviaN" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_LDLCshoxCMSTORM_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC shox * CMSTORM" "seized,,Zeu$,Edward,starix,GuardviaN" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_LDLCkiokiNgoCMSTORM_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC kiokiNgo * CMSTORM" "seized,,Zeu$,Edward,starix,GuardviaN" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_Zeu_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Zeu$" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC SMITHZZ * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC Happy * CMSTORM" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_starix_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "starix" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC SMITHZZ * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC Happy * CMSTORM" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_LDLCHappyCMSTORM_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC Happy * CMSTORM" "seized,,Zeu$,Edward,starix,GuardviaN" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_LDLCSMITHZZCMSTORM_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC SMITHZZ * CMSTORM" "seized,,Zeu$,Edward,starix,GuardviaN" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_GuardviaN_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "GuardviaN" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC SMITHZZ * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC Happy * CMSTORM" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/334_natus-vincere-team-ldlc_de_inferno/334_natus-vincere-team-ldlc_de_inferno_Edward_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Edward" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC SMITHZZ * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC Happy * CMSTORM" 0 334_natus-vincere-team-ldlc_de_inferno.dem ${pass}
#
#
#
##320_titan-epsilon_de_cache
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_EPSILONMAJ3R_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON MAJ3R" "Ex6TenZ,,Maniac,apEX[D],KQLY,kennyS" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_EPSILONGMXNike_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON G[M]X * Nike" "Ex6TenZ,,Maniac,apEX[D],KQLY,kennyS" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_Ex6TenZ_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Ex6TenZ" "EPSILON MAJ3R,,EPSILON G[M]X * Nike,EPSILON • SIXER/j/,EPSILON • Uzzziii * ViewSonic,EPSILON • ScreaM -R-" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_EPSILONUzzziiiViewSonic_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON • Uzzziii * ViewSonic" "Ex6TenZ,,Maniac,apEX[D],KQLY,kennyS" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_Maniac_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Maniac" "EPSILON MAJ3R,,EPSILON G[M]X * Nike,EPSILON • SIXER/j/,EPSILON • Uzzziii * ViewSonic,EPSILON • ScreaM -R-" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_KQLY_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "KQLY" "EPSILON MAJ3R,,EPSILON G[M]X * Nike,EPSILON • SIXER/j/,EPSILON • Uzzziii * ViewSonic,EPSILON • ScreaM -R-" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_EPSILONScreaMR_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON • ScreaM -R-" "Ex6TenZ,,Maniac,apEX[D],KQLY,kennyS" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_EPSILONSIXERj_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "EPSILON • SIXER/j/" "Ex6TenZ,,Maniac,apEX[D],KQLY,kennyS" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_kennyS_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "kennyS" "EPSILON MAJ3R,,EPSILON G[M]X * Nike,EPSILON • SIXER/j/,EPSILON • Uzzziii * ViewSonic,EPSILON • ScreaM -R-" 0 320_titan-epsilon_de_cache.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/320_titan-epsilon_de_cache/320_titan-epsilon_de_cache_apEXD_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "apEX[D]" "EPSILON MAJ3R,,EPSILON G[M]X * Nike,EPSILON • SIXER/j/,EPSILON • Uzzziii * ViewSonic,EPSILON • ScreaM -R-" 0 320_titan-epsilon_de_cache.dem ${pass}
#
#
#
##335_natus-vincere-team-ldlc_de_dust2
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_seized_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "seized" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC Happy * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC SMITHZZ * CMSTORM" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_LDLCNBeardKCMSTORM_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC NBeardK- * CMSTORM" "seized,,starix,Edward,Zeu$,GuardviaN" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_LDLCshoxCMSTORM_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC shox * CMSTORM" "seized,,starix,Edward,Zeu$,GuardviaN" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_LDLCkiokiNgoCMSTORM_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC kiokiNgo * CMSTORM" "seized,,starix,Edward,Zeu$,GuardviaN" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_LDLCSMITHZZCMSTORM_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC SMITHZZ * CMSTORM" "seized,,starix,Edward,Zeu$,GuardviaN" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_starix_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "starix" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC Happy * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC SMITHZZ * CMSTORM" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_LDLCHappyCMSTORM_0.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "LDLC Happy * CMSTORM" "seized,,starix,Edward,Zeu$,GuardviaN" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_Zeu_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Zeu$" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC Happy * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC SMITHZZ * CMSTORM" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_GuardviaN_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "GuardviaN" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC Happy * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC SMITHZZ * CMSTORM" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}
#python computeVisibility.py ${script_dir}/videos/335_natus-vincere-team-ldlc_de_dust2/335_natus-vincere-team-ldlc_de_dust2_Edward_1.mp4 ${script_dir}/../local_data/visibilities/ ${script_dir}/visibilityLogs/ "Edward" "LDLC NBeardK- * CMSTORM,,LDLC shox * CMSTORM,LDLC Happy * CMSTORM,LDLC kiokiNgo * CMSTORM,LDLC SMITHZZ * CMSTORM" 0 335_natus-vincere-team-ldlc_de_dust2.dem ${pass}


