call conda activate csknow
SET script_dir=%~dp0

cd %script_dir%csknow-python-analytics\visibility

python recordGameplay.py %script_dir%visibilitySignImages\tick0.png C:\Users\Administrator\Videos\ 319_titan-epsilon_de_dust2_pre_load_EPSILONMAJ3R_1.cfg,319_titan-epsilon_de_dust2_pre_load_apEXD_0.cfg,319_titan-epsilon_de_dust2_pre_load_EPSILONSIXERj_1.cfg,319_titan-epsilon_de_dust2_pre_load_EPSILONUzzziiiViewSonic_1.cfg,319_titan-epsilon_de_dust2_pre_load_Ex6TenZ_0.cfg,319_titan-epsilon_de_dust2_pre_load_EPSILONGMXNike_1.cfg,319_titan-epsilon_de_dust2_pre_load_EPSILONScreaMR_1.cfg,319_titan-epsilon_de_dust2_pre_load_Maniac_0.cfg,319_titan-epsilon_de_dust2_pre_load_KQLY_0.cfg,319_titan-epsilon_de_dust2_pre_load_kennyS_0.cfg

cd %script_dir%
